name: register-environment

on:
  workflow_call:
    inputs:
      environment_file:
        required: true
        type: string          # Path to env schema YAML (environment.schema.json)
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      conda_file:
        required: false
        default: ""
        type: string          # Optional: separate conda yaml to override
      dockerfile_path:
        required: false
        default: ""
        type: string          # Optional: folder containing Dockerfile for build context
    secrets:
      creds:
        required: true

jobs:
  register-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.creds }}

      - name: Install/Update Azure ML CLI extension
        run: |
          set -euo pipefail
          az extension add -n ml -y || az extension update -n ml

      - name: Set AML defaults
        run: |
          set -euo pipefail
          az configure --defaults \
            group="${{ inputs.resource_group }}" \
            workspace="${{ inputs.workspace_name }}" \
            location="eastus"
          az ml workspace show -o table

      # Mode A: env from YAML + CONDA override
      - name: Create environment (YAML + conda override)
        if: ${{ inputs.conda_file != '' && inputs.dockerfile_path == '' }}
        env:
          ENV_FILE: ${{ github.workspace }}/${{ inputs.environment_file }}
          CONDA_FILE: ${{ github.workspace }}/${{ inputs.conda_file }}
        run: |
          set -euo pipefail
          az ml environment create --file "$ENV_FILE" --conda-file "$CONDA_FILE"

      # Mode B: env from YAML + Docker build context
      - name: Create environment (YAML + Docker build context)
        if: ${{ inputs.dockerfile_path != '' && inputs.conda_file == '' }}
        env:
          ENV_FILE: ${{ github.workspace }}/${{ inputs.environment_file }}
          BUILD_CTX: ${{ github.workspace }}/${{ inputs.dockerfile_path }}
        run: |
          set -euo pipefail
          az ml environment create --file "$ENV_FILE" --build-context "$BUILD_CTX"

      # Mode C: env from YAML only
      - name: Create environment (YAML only)
        if: ${{ inputs.conda_file == '' && inputs.dockerfile_path == '' }}
        env:
          ENV_FILE: ${{ github.workspace }}/${{ inputs.environment_file }}
        run: |
          set -euo pipefail
          az ml environment create --file "$ENV_FILE"

      - name: List environments
        run: az ml environment list -o table



