name: run-pipeline

on:
  workflow_call:
    inputs:
      parameters_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      job_name:             # prefix; we'll add a unique suffix
        required: true
        type: string
    secrets:
      creds:
        required: true

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.creds }}

      - name: Install/Update ML extension
        run: |
          az extension add -n ml -y || true
          az extension update -n ml

      - name: Show inputs and repo tree
        run: |
          set -e
          echo "RG=${{ inputs.resource_group }}"
          echo "WS=${{ inputs.workspace_name }}"
          echo "JOB_PREFIX=${{ inputs.job_name }}"
          echo "PARAMS=${{ inputs.parameters_file }}"
          ls -la
          echo "-----"
          DIR="$(dirname "${{ inputs.parameters_file }}")"
          if [ -d "$DIR" ]; then ls -la "$DIR"; fi

      - name: Submit pipeline (unique name + default compute + stream)
        run: |
          set -euo pipefail

          # Build a UNIQUE job name to avoid immutable-name errors
          JOB_NAME="${{ inputs.job_name }}-${{ github.run_id }}-${{ github.run_attempt }}"
          echo "Submitting AML job: $JOB_NAME"

          az ml job create \
            --file "${{ github.workspace }}/${{ inputs.parameters_file }}" \
            --resource-group "${{ inputs.resource_group }}" \
            --workspace-name "${{ inputs.workspace_name }}" \
            --name "$JOB_NAME" \
            --set settings.default_compute=azureml:test-cluster \
            --only-show-errors --stream

          echo "Submission completed for: $JOB_NAME"

