name: deploy-model-training-pipeline

on:
  # Enables the "Run workflow" button in the Actions tab
  workflow_dispatch:
  # Auto-run on pushes / PRs to main
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Avoid overlapping runs from the same ref
concurrency:
  group: deploy-model-training-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1) Read workspace & resource group from repo config
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml

  # 2) Create/reuse AML compute cluster
  create-compute:
    needs: get-config
    uses: ./.github/workflows/custom-create-compute.yml
    with:
      cluster_name: test-cluster
      size: Standard_DS11_v2
      min_instances: 0
      max_instances: 1
      cluster_tier: dedicated
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  # 3) Register the used-cars dataset
  register-dataset:
    needs: get-config
    uses: ./.github/workflows/custom-register-dataset.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: used-cars-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  # 4) Register the training environment
  register-environment:
    needs: get-config
    uses: ./.github/workflows/custom-register-environment.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      environment_file: mlops/azureml/train/train-env.yml
      conda_file: data-science/environment/train-conda.yml
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  # 5) Run the AML pipeline (prep → sweep train → register best)
  run-pipeline:
    needs: [ get-config, register-environment, create-compute, register-dataset ]
    uses: ./.github/workflows/custom-run-pipeline.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: mlops/azureml/train/newpipeline.yml   # must match reusable workflow input name
      job-name: mlops-pipeline                               # must match reusable workflow input name
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
