name: deploy-model-training-pipeline

on:
  workflow_dispatch: {}     # <-- enables manual runs from the Actions tab
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: deploy-model-training-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1) Read workspace & RG from your repo config file
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml

  # 2) Create (or reuse) the AML compute cluster
  create-compute:
    needs: get-config
    uses: ./.github/workflows/custom-create-compute.yml
    with:
      cluster_name: test-cluster
      size: Standard_DS11_v2
      min_instances: 0
      max_instances: 1
      cluster_tier: dedicated
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  # 3) Register the used-cars dataset
  register-dataset:
    needs: get-config
    uses: ./.github/workflows/custom-register-dataset.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: used-cars-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  # 4) Register the training environment
  register-environment:
    needs: get-config
    uses: ./.github/workflows/custom-register-environment.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      environment_file: mlops/azureml/train/train-env.yml
      conda_file: train-conda.yml
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  # 5) Run the AML pipeline (preprocess → sweep train → register best)
  run-pipeline:
    needs: [ get-config, register-environment, create-compute, register-dataset ]
    uses: ./.github/workflows/custom-run-pipeline.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters_file: mlops/azureml/train/newpipeline.yml   # must match input name in reusable workflow
      job_name: mlops-pipeline                               # must match input name in reusable workflow
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
